name = "quiz-pub"
#workers_dev = true
compatibility_date = "2023-05-09"
# Add your account ID here
#account_id = "d29e0849d7ae4cc789c434548085883a"

main = "worker.mjs"

kv_namespaces = [
    { binding = "QUIZ_PUB_KV", id = "ab3dcafb2f1a40cf974e3ed6a87230bf" }
]

durable_objects.bindings = [
    { name = "rooms", class_name = "ChatRoom" },
]

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]
